// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AnalyzeExcel(arg1:string):Promise<void>;

export function Greet(arg1:string):Promise<string>;

export function OpenFileDialog():Promise<string>;

export function SaveExcel():Promise<void>;
