name: Release ExcelAnalyzer

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
        include:
          - os: windows-latest
            platform: windows
            arch: amd64
            ext: .exe
          - os: macos-latest
            platform: darwin
            arch: amd64
            ext: ""

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.22"

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20"

      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build Wails Project
        run: |
          wails build -platform ${{ matrix.platform }}/${{ matrix.arch }}

      - name: Rename Binary
        run: |
          mv build/bin/ExcelAnalyzer${{ matrix.ext }} build/bin/ExcelAnalyzer_${{ github.ref_name }}_${{ matrix.platform }}_${{ matrix.arch }}${{ matrix.ext }}

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/bin/ExcelAnalyzer_${{ github.ref_name }}_${{ matrix.platform }}_${{ matrix.arch }}${{ matrix.ext }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
